"""sync schema

Revision ID: 66c63869fecd
Revises: 
Create Date: 2025-12-18 14:05:25.626513

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '66c63869fecd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('store')
    op.drop_table('location_logs')
    op.drop_table('employee')
    op.drop_table('shift')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('pin',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('employees_pin_key'), type_='unique')

    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clock_in', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('clock_out', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('employee_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('store_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('gps_pings')
        batch_op.drop_column('paid_minutes')
        batch_op.drop_column('status')
        batch_op.drop_column('geofence_flag')
        batch_op.drop_column('clock_out_time')
        batch_op.drop_column('last_gps_ping')
        batch_op.drop_column('missed_clock_out_flag')
        batch_op.drop_column('clock_in_time')

    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_token', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('geofence_radius_m', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('stores_qr_code_token_key'), type_='unique')
        batch_op.create_unique_constraint(None, ['qr_token'])
        batch_op.drop_column('geofence_radius_meters')
        batch_op.drop_column('qr_code_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_code_token', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('geofence_radius_meters', sa.INTEGER(), server_default=sa.text('200'), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('stores_qr_code_token_key'), ['qr_code_token'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('geofence_radius_m')
        batch_op.drop_column('qr_token')

    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clock_in_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('missed_clock_out_flag', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('last_gps_ping', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('clock_out_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('geofence_flag', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'open'::character varying"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('paid_minutes', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('gps_pings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True))
        batch_op.alter_column('store_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('employee_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('clock_out')
        batch_op.drop_column('clock_in')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('employees_pin_key'), ['pin'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('pin',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('active')

    op.create_table('shift',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('store_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('clock_in', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('clock_out', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('in_lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('in_lon', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('out_lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('out_lon', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], name=op.f('shift_employee_id_fkey')),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], name=op.f('shift_store_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('shift_pkey'))
    )
    op.create_table('employee',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('qr_code', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('employee_pkey')),
    sa.UniqueConstraint('qr_code', name=op.f('employee_qr_code_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('location_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('shift_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('lng', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], name=op.f('location_logs_shift_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('location_logs_pkey'))
    )
    op.create_table('store',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('radius_meters', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('store_pkey'))
    )
    # ### end Alembic commands ###
