"""Add admin override audit fields to shifts

Revision ID: e66647d1c75c
Revises: 66c63869fecd
Create Date: 2025-12-19 10:12:07.801765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e66647d1c75c'
down_revision = '66c63869fecd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('pin', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('qr_token', sa.String(length=120), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('geofence_radius_m', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qr_token')
    )
    op.create_table('shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('clock_in', sa.DateTime(), nullable=False),
    sa.Column('clock_out', sa.DateTime(), nullable=True),
    sa.Column('clock_in_lat', sa.Float(), nullable=True),
    sa.Column('clock_in_lng', sa.Float(), nullable=True),
    sa.Column('clock_out_lat', sa.Float(), nullable=True),
    sa.Column('clock_out_lng', sa.Float(), nullable=True),
    sa.Column('closed_by_admin', sa.Boolean(), nullable=False),
    sa.Column('admin_closed_by', sa.String(length=120), nullable=True),
    sa.Column('admin_closed_at', sa.DateTime(), nullable=True),
    sa.Column('admin_close_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('admin')
    op.drop_table('employee')
    op.drop_table('shift')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('employee_id', sa.INTEGER(), nullable=False),
    sa.Column('clock_in_at', sa.DATETIME(), nullable=False),
    sa.Column('clock_out_at', sa.DATETIME(), nullable=True),
    sa.Column('clock_in_lat', sa.FLOAT(), nullable=True),
    sa.Column('clock_in_lng', sa.FLOAT(), nullable=True),
    sa.Column('clock_out_lat', sa.FLOAT(), nullable=True),
    sa.Column('clock_out_lng', sa.FLOAT(), nullable=True),
    sa.Column('is_open', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('qr_code', sa.VARCHAR(length=200), nullable=False),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qr_code')
    )
    op.create_table('admin',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=200), nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.drop_table('shifts')
    op.drop_table('stores')
    op.drop_table('employees')
    # ### end Alembic commands ###
